<?xml version="1.0" encoding="utf-8"?><Database Name="ans" Class="DataClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-MHA8L15;Initial Catalog=ans;Integrated Security=True" SettingsObjectName="ANSIS_V3.Properties.Settings" SettingsPropertyName="ansConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserType" Member="UserTypes">
    <Type Name="UserType">
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="UserType_UserAccount" Member="UserAccounts" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="UserAccount" />
    </Type>
  </Table>
  <Table Name="dbo.UserAccount" Member="UserAccounts">
    <Type Name="UserAccount">
      <Column Name="UserAccountID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middlename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="AccessCode" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="UserType_UserAccount" Member="UserType" ThisKey="UserTypeID" OtherKey="UserTypeID" Type="UserType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schoolyear" Member="Schoolyears">
    <Type Name="Schoolyear">
      <Column Name="SchoolyearID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Year" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Schoolyear_Student" Member="Students" ThisKey="SchoolyearID" OtherKey="SchoolyearID" Type="Student" />
    </Type>
  </Table>
  <Table Name="dbo.Subject" Member="Subjects">
    <Type Name="Subject">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Subject" Member="Subject1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Subject_Teacher" Member="Teachers" ThisKey="SubjectID" OtherKey="SubjectID" Type="Teacher" />
    </Type>
  </Table>
  <Table Name="dbo.Teacher" Member="Teachers">
    <Type Name="Teacher">
      <Column Name="TeacherID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middlename" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SubjectID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Teacher_Section" Member="Sections" ThisKey="TeacherID" OtherKey="TeacherID" Type="Section" />
      <Association Name="Subject_Teacher" Member="Subject" ThisKey="SubjectID" OtherKey="SubjectID" Type="Subject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimeSchedule" Member="TimeSchedules">
    <Type Name="TimeSchedule">
      <Column Name="TimeScheduleID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TimeStart" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TimeEnd" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Section" Member="Sections">
    <Type Name="Section">
      <Column Name="SectionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Section" Member="Section1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="YearLevel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TeacherID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Section_Student" Member="Students" ThisKey="SectionID" OtherKey="SectionID" Type="Student" />
      <Association Name="Teacher_Section" Member="Teacher" ThisKey="TeacherID" OtherKey="TeacherID" Type="Teacher" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="StudentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Middlname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ParentName" Type="System.String" DbType="VarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="ParentNo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Occupation" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(5,2) NOT NULL" CanBeNull="false" />
      <Column Name="Systolic" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Diastolic" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Form137" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Form138" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="GoodMoral" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NSO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="YearLevel" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SectionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SchoolyearID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Schoolyear_Student" Member="Schoolyear" ThisKey="SchoolyearID" OtherKey="SchoolyearID" Type="Schoolyear" IsForeignKey="true" />
      <Association Name="Section_Student" Member="Section" ThisKey="SectionID" OtherKey="SectionID" Type="Section" IsForeignKey="true" />
    </Type>
  </Table>
</Database>